name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - dev

jobs:
  test-and-sonar:
    name: Run Tests and SonarQube Analysis
    runs-on: ubuntu-latest
    environment: test

    steps:
      # 1. Clona el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configura Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Usa la versión compatible con tu proyecto

      # 3. Instala dependencias
      - name: Install dependencies
        run: npm install

      # 4. Ejecuta los tests con cobertura
      - name: Run tests with coverage
        run: npm test -- --coverage
        continue-on-error: true

      # 5. Subir resultados a SonarQube
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    name: Deploy to GitHub Pages
    needs: test-and-sonar
    runs-on: ubuntu-latest

    steps:
      # 1. Clona el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configura Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3. Instala dependencias
      - name: Install dependencies
        run: npm install

      # 4. Construye el proyecto para producción
      - name: Build project
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
